### ISSUE TITLE
Todo List Delete and Rename

### ISSUE THREAD

**Issue by ghost** [mivoligo/Zeegaree#5]
How to rename or delete a todo list?

**Comment by mivoligo** [comment]
The main todo list, which is named "ToDo List" can't be deleted or renamed.
However you can create other todo lists which you can later rename or delete. In order to do that:
1. Open "Tasks" panel
2. Click the "hamburger" icon next to "ToDo List"
3. Select "Show Lists"
Now you can create another todo list by clicking "New List of Tasks" button
Later in the "List" view, you can click the "hamburger" icon next to the name of a list and there you'll have option to "Delete" the list or "Edit" its name.
As I mentioned before, you can't rename or delete the main "ToDo List".
